language: node_js
node_js:
  - "12.8.0"
cache:
  directories:
    - node_modules
before_install:
  - pip install --user codecov
script:
  - yarn run test:coverage
  - yarn run check-types
  - yarn run lint
  - yarn run build
after_success:
  - codecov --file coverage/lcov.info --disable search
