language: node_js
node_js:
  - "12.8.0"
cache:
  directories:
    - node_modules
before_install:
  - pip install --user codecov
script:
  - yarn run test:coverage
  - yarn run build
after_success:
  - codecov --file coverage/lcov.info --disable search
before_deploy:
  - yarn global add netlify-cli
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN -p --dir ./build --message "Deploy from Travis"
  skip_cleanup: true
  on: 
    branch: master
